# This is a basic workflow to help you get started with Actions

name: AutoPack

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      folder:
        description: "Enter folder you wanna pack"
        required: true
        default: "Unpack"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup environment
        run: |
          cd ~
          sudo apt-get update && sudo apt-get install cmake git build-essential -y
          git clone https://github.com/nextgal/pfs_upk.git
          mkdir pfs_upk/build && cd pfs_upk/build
          cmake .. && make
          sudo ln pfs_upk /bin/pfs_upk
          
      - name: Pack folder into Artemis pfs file
        run: |
          ls
          cd ${{ github.workspace }}
          pfs_upk ${{ github.event.inputs.folder }}
        
      - name: Upload pfs file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.folder }}.pfs
          path: "${{ github.workspace }}/${{ github.event.inputs.folder }}.pfs"
