# This is a basic workflow to help you get started with Actions

name: Auto_Pack

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      folder:
        description: "Enter folder you wanna pack"
        required: true
        default: "Unpack"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup environment
        run: |
          echo --- Change locale to ja_JP.UTF-8 ---
          sudo apt-get update && sudo apt-get install language-pack-ja
          sudo localectl set-locale LANG="ja_JP.UTF-8"
          export LANG="ja_JP.UTF-8"
          sudo update-locale
          echo --- Install cmake ---
          cd ~
          sudo apt-get install cmake git build-essential -y
          echo --- Build pfs_upk ---
          git clone -b test https://github.com/shenglin00/pfs_upk.git
          mkdir pfs_upk/build && cd pfs_upk/build
          cmake .. && make
          sudo ln pfs_upk /bin/pfs_upk
          
      - name: Pack folder into Artemis pfs file
        run: |
          pfs_upk ${{ github.event.inputs.folder }}
          if [ ! -f "${{ github.event.inputs.folder }}.pfs" ]; then
            echo Error: ${{ github.event.inputs.folder }}.pfs not found.
            exit 404
          fi
        
      - name: Upload pfs file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.folder }}.pfs
          path: "${{ github.workspace }}/${{ github.event.inputs.folder }}.pfs"
